# Generated by Django 2.2.6 on 2019-10-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendMail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='Email',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
